export const LOGIN_SIGNUP_REQUEST = "LOGIN_SIGNUP_REQUEST";
export const LOGIN_SIGNUP_SUCCESS = "LOGIN_SIGNUP_SUCCESS";
export const LOGIN_SIGNUP_FAIL = "LOGIN_SIGNUP_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const CLEAR_ERROR = "CLEAR_ERROR";